### ISSUE TITLE
[Bug]: Can`t run the Basic 1.1 Serverpack

### ISSUE THREAD

**Issue by Rezondes** [dr3ams/Roguelike-Adventures-and-Dungeons-2#219]
### General Info

- [x] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Linux Debian

### Modpack version

1.1

### Describe your issue

I can't start the server with the default files.

### Steps to reproduce the issue

1. Download Serverfiles
2. Unpack Zip
3. Run the Bat-File

### Additional Information

Crashreport:
[crash-2023-03-07_20.37.47-fml.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10913767/crash-2023-03-07_20.37.47-fml.txt)

**Comment by KimoKat** [comment]
Similar issue; server files sent to BisectHosting do not match up with the client versions for many of the mods. Had to backup to 1.0a until this is resolved. 

Using BisectHosting for the server.
Myself and my friends use Overwolf (CurseForge's App) to download the pack. The singleplayer pack seems file and working, the server files are missing some mods though.

**Comment by ImCoolio** [comment]
+1 Happening to me and my friends as well.

**Comment by Redeye123** [comment]
looks like java 11 "Java Version: 11.0.18, Debian" try java 8 since its 1.16.5

I had the same issue but changing the startup to using java 8 solved it

**Comment by ImCoolio** [comment]
> looks like java 11 "Java Version: 11.0.18, Debian" try java 8 since its 1.16.5
> 
> I had the same issue but changing the startup to using java 8 solved it

It's not that. My friend was using a compatible version of Java and it still wouldn't let him join, likewise with me on Xubuntu Linux. It's just the BetterDefaultBiomes file having a space in it causing some issues in the modlist crosschecking with the client.

**Comment by DoctorMage** [comment]
@Rezondes https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/58

**Comment by bashbers** [comment]
Im running a clean install of 1.1 but get the same errors as above. I've tried using JDK8_212, both on Alpine and ubuntu but after reading further into error I found this thread: https://github.com/CreativeMD/ItemPhysicLite/issues/7#issuecomment-952679473
It seems like the server pack has **Item Physics Lite** and is trying to load it serverside which causes the error.

After excluding **ItemPhysicsLite** I ran into **Oculus**, another clientside only mod which gave a similar error. Here is a thread: https://github.com/Asek3/Oculus/issues/279#issuecomment-1398434877

Same for **ItemBorders**: https://www.curseforge.com/minecraft/mc-mods/item-borders
And the same for **legendarytooltips** https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips
And the same for **CraftPresence**: https://www.curseforge.com/minecraft/mc-mods/craftpresence
And the same for **BetterF3** https://www.curseforge.com/minecraft/mc-mods/betterf3

After removing these clientside mods from the servermods mods folder, the server started working for me.
Here is an exhaustive list of CurseForge ID's for those who are using itzg's docker minecraft server:

```
version: '3'

services:
  minecraft:
    image: itzg/minecraft-server:java8
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - "./mc:/data"
    environment:
      - EULA=TRUE
      - MEMORY=8G
      - VERSION=1.16.5
      - TYPE=AUTO_CURSEFORGE
      - CF_SLUG=roguelike-adventures-and-dungeons-2
      - CF_FILENAME_MATCHER=-1.1
      - CF_EXCLUDE_MODS=270441,581495,513769,532127,297038,401648
    tty: true
    stdin_open: true
```
